# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FinalCompOver2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import select
from random import random

from PyQt5 import QtCore, QtGui, QtWidgets
import json
import socket

from PyQt5.QtGui import QKeySequence
from PyQt5.QtWidgets import QApplication, QShortcut

import interpreter

from EmulatorGUI import GPIO

try_setup = True


class Ui_Form(object):

    def closeEvent(self, event):
        print("User has clicked the red x on the main window")
        event.accept()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1486, 1050)
        Form.setMinimumSize(QtCore.QSize(900, 800))
        Form.setMaximumSize(QtCore.QSize(2000, 1050))

        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(-20, 0, 1531, 1050))
        self.graphicsView.setMaximumSize(QtCore.QSize(1600, 1050))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setStyleSheet("border-image: url(:/newPrefix/Resize_1.jpg);")
        self.graphicsView.setObjectName("graphicsView")

        self.Overlay_Opacity = QtWidgets.QTextBrowser(Form)
        self.Overlay_Opacity.setGeometry(QtCore.QRect(-30, -30, 1521, 1081))
        self.Overlay_Opacity.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.Overlay_Opacity.setObjectName("Overlay_Opacity")

        self.Bus_Text = QtWidgets.QTextBrowser(Form)
        self.Bus_Text.setGeometry(QtCore.QRect(590, 30, 301, 141))
        self.Bus_Text.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Bus_Text.setObjectName("Bus_Text")
        self.Bus_LCD = QtWidgets.QLCDNumber(Form)
        self.Bus_LCD.setGeometry(QtCore.QRect(620, 90, 231, 61))
        self.Bus_LCD.setObjectName("Bus_LCD")

        self.Ram_Contents = QtWidgets.QTextBrowser(Form)
        self.Ram_Contents.setGeometry(QtCore.QRect(40, 390, 561, 291))
        self.Ram_Contents.setStyleSheet("background-color: rgba(125, 125, 125, 210);")
        self.Ram_Contents.setObjectName("Ram_Contents")

        self.Clock_Text = QtWidgets.QTextBrowser(Form)
        self.Clock_Text.setGeometry(QtCore.QRect(200, 40, 231, 111))
        self.Clock_Text.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Clock_Text.setObjectName("Clock_Text")

        self.Program_Counter = QtWidgets.QTextBrowser(Form)
        self.Program_Counter.setGeometry(QtCore.QRect(1030, 30, 281, 151))
        self.Program_Counter.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Program_Counter.setObjectName("Program_Counter")
        self.Program_Counter_LCD = QtWidgets.QLCDNumber(Form)
        self.Program_Counter_LCD.setGeometry(QtCore.QRect(1070, 80, 201, 61))
        self.Program_Counter_LCD.setObjectName("Program_Counter_LCD")

        self.Memory_Instruction = QtWidgets.QTextBrowser(Form)
        self.Memory_Instruction.setGeometry(QtCore.QRect(190, 190, 261, 131))
        self.Memory_Instruction.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Memory_Instruction.setObjectName("Memory_Instruction")
        self.Memory_LCD = QtWidgets.QLCDNumber(Form)
        self.Memory_LCD.setGeometry(QtCore.QRect(220, 240, 181, 51))
        self.Memory_LCD.setObjectName("Memory_LCD")

        self.State_Description_Text = QtWidgets.QTextBrowser(Form)
        self.State_Description_Text.setGeometry(QtCore.QRect(520, 780, 681, 141))
        self.State_Description_Text.setStyleSheet("background-color: rgba(222, 222, 222, 210);")
        self.State_Description_Text.setObjectName("State_Description_Text")

        self.Instruction_Register = QtWidgets.QTextBrowser(Form)
        self.Instruction_Register.setGeometry(QtCore.QRect(150, 750, 311, 51))
        self.Instruction_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Instruction_Register.setObjectName("Instruction_Register")
        self.Instruction_Text = QtWidgets.QTextBrowser(Form)
        self.Instruction_Text.setGeometry(QtCore.QRect(150, 800, 311, 161))
        self.Instruction_Text.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Instruction_Text.setObjectName("Instruction_Text")

        self.Flag_Register = QtWidgets.QTextEdit(Form)
        self.Flag_Register.setGeometry(QtCore.QRect(1270, 810, 171, 121))
        self.Flag_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Flag_Register.setObjectName("Flag_Register")
        self.Carry_Flag = QtWidgets.QCheckBox(Form)
        self.Carry_Flag.setEnabled(True)
        self.Carry_Flag.setGeometry(QtCore.QRect(1330, 870, 81, 20))
        self.Carry_Flag.setText("")
        self.Carry_Flag.setChecked(True)
        self.Carry_Flag.setObjectName("Carry_Flag")
        self.Zero_Flag = QtWidgets.QCheckBox(Form)
        self.Zero_Flag.setGeometry(QtCore.QRect(1330, 890, 81, 20))
        self.Zero_Flag.setText("")
        self.Zero_Flag.setChecked(True)
        self.Zero_Flag.setObjectName("Zero_Flag")

        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(850, 290, 631, 441))
        self.groupBox.setStyleSheet("background-color: rgba(107, 135, 85, 175);\n")
        self.groupBox.setObjectName("groupBox")

        self.B_Register = QtWidgets.QTextBrowser(self.groupBox)
        self.B_Register.setGeometry(QtCore.QRect(330, 200, 211, 111))
        self.B_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.B_Register.setObjectName("B_Register")
        self.B_LCD = QtWidgets.QLCDNumber(self.groupBox)
        self.B_LCD.setGeometry(QtCore.QRect(360, 260, 161, 41))
        self.B_LCD.setObjectName("B_LCD")

        self.A_Register = QtWidgets.QTextBrowser(self.groupBox)
        self.A_Register.setGeometry(QtCore.QRect(330, 40, 211, 111))
        self.A_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.A_Register.setObjectName("A_Register")
        self.A_LCD = QtWidgets.QLCDNumber(self.groupBox)
        self.A_LCD.setGeometry(QtCore.QRect(350, 100, 171, 41))
        self.A_LCD.setObjectName("A_LCD")

        self.Output_Register = QtWidgets.QTextBrowser(self.groupBox)
        self.Output_Register.setGeometry(QtCore.QRect(100, 340, 291, 61))
        self.Output_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Output_Register.setObjectName("Output_Register")
        self.Output_LCD = QtWidgets.QLCDNumber(self.groupBox)
        self.Output_LCD.setGeometry(QtCore.QRect(390, 330, 241, 81))
        self.Output_LCD.setStyleSheet("")
        self.Output_LCD.setObjectName("Output_LCD")


        self.Sum_Register = QtWidgets.QTextBrowser(self.groupBox)
        self.Sum_Register.setGeometry(QtCore.QRect(40, 130, 211, 111))
        self.Sum_Register.setStyleSheet("background-color: rgba(107, 107, 107, 200);")
        self.Sum_Register.setObjectName("Sum_Register")
        self.Sum_LCD = QtWidgets.QLCDNumber(self.groupBox)
        self.Sum_LCD.setGeometry(QtCore.QRect(60, 180, 161, 41))
        self.Sum_LCD.setObjectName("Sum_LCD")




        self.RR_2 = QtWidgets.QTextBrowser(Form)
        self.RR_2.setGeometry(QtCore.QRect(40, 470, 81, 31))
        self.RR_2.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_2.setObjectName("RR_2")
        self.RR_1 = QtWidgets.QTextBrowser(Form)
        self.RR_1.setGeometry(QtCore.QRect(40, 440, 81, 31))
        self.RR_1.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_1.setObjectName("RR_1")
        self.RR_3 = QtWidgets.QTextBrowser(Form)
        self.RR_3.setGeometry(QtCore.QRect(40, 500, 81, 31))
        self.RR_3.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_3.setObjectName("RR_3")
        self.RR_4 = QtWidgets.QTextBrowser(Form)
        self.RR_4.setGeometry(QtCore.QRect(40, 530, 81, 31))
        self.RR_4.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_4.setObjectName("RR_4")
        self.RR_6 = QtWidgets.QTextBrowser(Form)
        self.RR_6.setGeometry(QtCore.QRect(40, 590, 81, 31))
        self.RR_6.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_6.setObjectName("RR_6")
        self.RR_7 = QtWidgets.QTextBrowser(Form)
        self.RR_7.setGeometry(QtCore.QRect(40, 620, 81, 31))
        self.RR_7.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_7.setObjectName("RR_7")
        self.RR_8 = QtWidgets.QTextBrowser(Form)
        self.RR_8.setGeometry(QtCore.QRect(40, 650, 81, 31))
        self.RR_8.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_8.setObjectName("RR_8")
        self.RR_5 = QtWidgets.QTextBrowser(Form)
        self.RR_5.setGeometry(QtCore.QRect(40, 560, 81, 31))
        self.RR_5.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_5.setObjectName("RR_5")
        self.RR_7_7 = QtWidgets.QTextBrowser(Form)
        self.RR_7_7.setGeometry(QtCore.QRect(120, 620, 201, 31))
        self.RR_7_7.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_7_7.setObjectName("RR_7_7")
        self.RR_4_4 = QtWidgets.QTextBrowser(Form)
        self.RR_4_4.setGeometry(QtCore.QRect(120, 530, 201, 31))
        self.RR_4_4.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_4_4.setObjectName("RR_4_4")
        self.RR_8_8 = QtWidgets.QTextBrowser(Form)
        self.RR_8_8.setGeometry(QtCore.QRect(120, 650, 201, 31))
        self.RR_8_8.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_8_8.setObjectName("RR_8_8")
        self.RR_3_3 = QtWidgets.QTextBrowser(Form)
        self.RR_3_3.setGeometry(QtCore.QRect(120, 500, 201, 31))
        self.RR_3_3.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_3_3.setObjectName("RR_3_3")
        self.RR_5_5 = QtWidgets.QTextBrowser(Form)
        self.RR_5_5.setGeometry(QtCore.QRect(120, 560, 201, 31))
        self.RR_5_5.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_5_5.setObjectName("RR_5_5")
        self.RR_1_1 = QtWidgets.QTextBrowser(Form)
        self.RR_1_1.setGeometry(QtCore.QRect(120, 440, 201, 31))
        self.RR_1_1.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_1_1.setObjectName("RR_1_1")
        self.RR_6_6 = QtWidgets.QTextBrowser(Form)
        self.RR_6_6.setGeometry(QtCore.QRect(120, 590, 201, 31))
        self.RR_6_6.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_6_6.setObjectName("RR_6_6")
        self.RR_2_2 = QtWidgets.QTextBrowser(Form)
        self.RR_2_2.setGeometry(QtCore.QRect(120, 470, 201, 31))
        self.RR_2_2.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_2_2.setObjectName("RR_2_2")
        self.RR_14_14 = QtWidgets.QTextBrowser(Form)
        self.RR_14_14.setGeometry(QtCore.QRect(400, 590, 201, 31))
        self.RR_14_14.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_14_14.setObjectName("RR_14_14")
        self.RR_15 = QtWidgets.QTextBrowser(Form)
        self.RR_15.setGeometry(QtCore.QRect(320, 620, 81, 31))
        self.RR_15.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_15.setObjectName("RR_15")
        self.RR_11_11 = QtWidgets.QTextBrowser(Form)
        self.RR_11_11.setGeometry(QtCore.QRect(400, 500, 201, 31))
        self.RR_11_11.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_11_11.setObjectName("RR_11_11")
        self.RR_12 = QtWidgets.QTextBrowser(Form)
        self.RR_12.setGeometry(QtCore.QRect(320, 530, 81, 31))
        self.RR_12.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_12.setObjectName("RR_12")
        self.RR_15_15 = QtWidgets.QTextBrowser(Form)
        self.RR_15_15.setGeometry(QtCore.QRect(400, 620, 201, 31))
        self.RR_15_15.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_15_15.setObjectName("RR_15_15")
        self.RR_16 = QtWidgets.QTextBrowser(Form)
        self.RR_16.setGeometry(QtCore.QRect(320, 650, 81, 31))
        self.RR_16.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_16.setObjectName("RR_16")
        self.RR_11 = QtWidgets.QTextBrowser(Form)
        self.RR_11.setGeometry(QtCore.QRect(320, 500, 81, 31))
        self.RR_11.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_11.setObjectName("RR_11")
        self.RR_16_16 = QtWidgets.QTextBrowser(Form)
        self.RR_16_16.setGeometry(QtCore.QRect(400, 650, 201, 31))
        self.RR_16_16.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_16_16.setObjectName("RR_16_16")
        self.RR_13 = QtWidgets.QTextBrowser(Form)
        self.RR_13.setGeometry(QtCore.QRect(320, 560, 81, 31))
        self.RR_13.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_13.setObjectName("RR_13")
        self.RR_9 = QtWidgets.QTextBrowser(Form)
        self.RR_9.setGeometry(QtCore.QRect(320, 440, 81, 31))
        self.RR_9.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_9.setObjectName("RR_9")
        self.RR_10_10 = QtWidgets.QTextBrowser(Form)
        self.RR_10_10.setGeometry(QtCore.QRect(400, 470, 201, 31))
        self.RR_10_10.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_10_10.setObjectName("RR_10_10")
        self.RR_13_13 = QtWidgets.QTextBrowser(Form)
        self.RR_13_13.setGeometry(QtCore.QRect(400, 560, 201, 31))
        self.RR_13_13.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_13_13.setObjectName("RR_13_13")
        self.RR_14 = QtWidgets.QTextBrowser(Form)
        self.RR_14.setGeometry(QtCore.QRect(320, 590, 81, 31))
        self.RR_14.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_14.setObjectName("RR_14")
        self.RR_9_9 = QtWidgets.QTextBrowser(Form)
        self.RR_9_9.setGeometry(QtCore.QRect(400, 440, 201, 31))
        self.RR_9_9.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_9_9.setObjectName("RR_9_9")
        self.RR_10 = QtWidgets.QTextBrowser(Form)
        self.RR_10.setGeometry(QtCore.QRect(320, 470, 81, 31))
        self.RR_10.setStyleSheet("background-color: rgba(80, 80, 80, 210);")
        self.RR_10.setObjectName("RR_10")
        self.RR_12_12 = QtWidgets.QTextBrowser(Form)
        self.RR_12_12.setGeometry(QtCore.QRect(400, 530, 201, 31))
        self.RR_12_12.setStyleSheet("background-color: rgba(100, 100, 100, 210);")
        self.RR_12_12.setObjectName("RR_12_12")
        self.graphicsView.raise_()
        self.Overlay_Opacity.raise_()
        self.Flag_Register.raise_()
        self.Carry_Flag.raise_()
        self.Zero_Flag.raise_()
        self.Instruction_Register.raise_()
        self.Clock_Text.raise_()
        self.Ram_Contents.raise_()
        self.Program_Counter.raise_()
        self.groupBox.raise_()
        self.Memory_Instruction.raise_()
        self.Instruction_Text.raise_()
        self.Bus_Text.raise_()
        self.State_Description_Text.raise_()
        self.Memory_LCD.raise_()
        self.Bus_LCD.raise_()
        self.Program_Counter_LCD.raise_()
        self.RR_2.raise_()
        self.RR_1.raise_()
        self.RR_3.raise_()
        self.RR_4.raise_()
        self.RR_6.raise_()
        self.RR_7.raise_()
        self.RR_8.raise_()
        self.RR_5.raise_()
        self.RR_7_7.raise_()
        self.RR_4_4.raise_()
        self.RR_8_8.raise_()
        self.RR_3_3.raise_()
        self.RR_5_5.raise_()
        self.RR_1_1.raise_()
        self.RR_6_6.raise_()
        self.RR_2_2.raise_()
        self.RR_14_14.raise_()
        self.RR_15.raise_()
        self.RR_11_11.raise_()
        self.RR_12.raise_()
        self.RR_15_15.raise_()
        self.RR_16.raise_()
        self.RR_11.raise_()
        self.RR_16_16.raise_()
        self.RR_13.raise_()
        self.RR_9.raise_()
        self.RR_10_10.raise_()
        self.RR_13_13.raise_()
        self.RR_14.raise_()
        self.RR_9_9.raise_()
        self.RR_10.raise_()
        self.RR_12_12.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


        self.Bus_Text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                    "p, li { white-space: pre-wrap; }\n"
                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                    "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bus Value</span></p></body></html>"))
        self.Ram_Contents.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">RAM Contents</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; color:#000000;\"><br /></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600; color:#000000;\"><br /></p></body></html>"))
        self.Clock_Text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Clock</span></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">No Power</span></p></body></html>"))
        self.Program_Counter.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Program Counter</span></p></body></html>"))
        self.Memory_Instruction.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Memory Instruction</span></p></body></html>"))
        self.State_Description_Text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Text Displays here.</span></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.Instruction_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Instruction Register</span></p></body></html>"))
        self.Flag_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Flag Register</span></p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\"> </span></p>\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Carry:</span></p>\n"
                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\"> Zero:</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Form", "Arithmetic Logic Unit"))
        self.B_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Register B</span></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.A_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Register A</span></p>\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Output_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Output Register</span></p></body></html>"))
        self.Sum_Register.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Sum Register</span></p></body></html>"))
        self.Instruction_Text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#000000;\">Current Instruction:</span></p></body></html>"))
        self.RR_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">2</span></p></body></html>"))
        self.RR_1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">1</span></p></body></html>"))
        self.RR_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">3</span></p></body></html>"))
        self.RR_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">4</span></p></body></html>"))
        self.RR_6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">6</span></p></body></html>"))
        self.RR_7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">7</span></p></body></html>"))
        self.RR_8.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">8</span></p></body></html>"))
        self.RR_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">5</span></p></body></html>"))
        self.RR_15.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">15</span></p></body></html>"))
        self.RR_12.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">12</span></p></body></html>"))
        self.RR_16.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">16</span></p></body></html>"))
        self.RR_11.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">11</span></p></body></html>"))
        self.RR_13.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">13</span></p></body></html>"))
        self.RR_9.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">9</span></p></body></html>"))
        self.RR_14.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">14</span></p></body></html>"))
        self.RR_10.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                        "p, li { white-space: pre-wrap; }\n"
                                        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                        "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">10</span></p></body></html>"))
import Background_rc_rc

def set_up_connection(source, ui, json_values, app, Form):
    # establish the base variables
    # if BE architecture, we're going to get stuff from the GPIO pins, then do the interpretation in a forever loop. Add some sort of exception later
    if (source == "True"):

        GPIO.setmode(GPIO.BCM)
        GPIO.setup(20, GPIO.IN)
        GPIO.setup(16, GPIO.IN)
        GPIO.setup(12, GPIO.IN)
        GPIO.setup(4, GPIO.IN)
        GPIO.setup(7, GPIO.IN)
        GPIO.setup(8, GPIO.IN)
        GPIO.setup(25, GPIO.IN)
        GPIO.setup(23, GPIO.IN)
        GPIO.setup(10, GPIO.IN)
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.bind(("", 9999))
        s.listen(1)
        # sock = socket.create_connection(("", 9999))
        conn, addr = s.accept()
        current_clock = None
        previous_clock = None
        conn.settimeout(.001)
        allValues = ["0", "00000000", "0000000000000000"]
        while True:
            allValues[2] = str(allValues[2][0:16])
            # print(allValues[0])
            # print(allValues[1])
            # print(allValues[2])
            current_clock = allValues[0]
            # to avoid over-interpretation and wrong results, only run the interpreter
            # and update results on every voltage switch
            # THIS PART IS IMPORTANT!! If it does not check for the current voltage and only update
            # when the voltage changes, it could produce wrong results when we bring this over to the GPIO
            if previous_clock is None or (current_clock == "0" and previous_clock == "1") or (
                    current_clock == "1" and previous_clock == "0"):
                json_values = interpreter.interpret(allValues, json_values)
                previous_clock = current_clock
                # Bus update
                ui.lcdNumber_3.display(json_values["ui_variables"]["bus_display"])

                # A register update
                ui.lcdNumber_4.display(json_values["ui_variables"]["a_register_display"])

                # B register update
                ui.lcdNumber_2.display(json_values["ui_variables"]["b_register_display"])

                # Output register update
                ui.lcdNumber.display(json_values["ui_variables"]["output_register_display"])

                ui.lcdNumber_5.display(json_values["ui_variables"]["program_counter"])

                # Instruction Register update
                ui.textBrowser_10.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                            "p, li { white-space: pre-wrap; }\n"
                                                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Instruction Register</span></p>\n"
                                                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br />" +
                                                                            json_values["ui_variables"][
                                                                                "instruction_register"] + "</p></body></html>"))

                # layman's intepretation update
                ui.textBrowser_9.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                           "p, li { white-space: pre-wrap; }\n"
                                                                           "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                           "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                           "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                           "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                           "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">" +
                                                                           json_values["ui_variables"][
                                                                               "laymans"] + "</span></p>\n"
                                                                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                                                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
                # carry flag update
                ui.Carry_Flag.setChecked(bool(json_values["ui_variables"]["carry_flag"]))

                # zero flag update
                ui.Zero_Flag.setChecked(bool(json_values["ui_variables"]["zero_flag"]))

                # Clock update
                ui.textBrowser_3.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                           "p, li { white-space: pre-wrap; }\n"
                                                                           "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                           "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                           "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Clock</span></p>\n"
                                                                           "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">" + interpreter.voltage + "</span></p></body></html>"))
                if allValues[0] == "1":
                    ui.textBrowser_3.setStyleSheet(
                        QtCore.QCoreApplication.translate("form", "background-color: rgb(255, 255, 204);"))
                    ui.textBrowser_3.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                               "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Clock</span></p>\n"
                                                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">" + interpreter.voltage + "</span></p></body></html>"))

                # laymans' interpretation
                else:
                    ui.textBrowser_3.setStyleSheet(
                        QtCore.QCoreApplication.translate("form", "background-color: rgba(107, 107, 107, 150);"))

            QtCore.QCoreApplication.processEvents()
            QtGui.QGuiApplication.quitOnLastWindowClosed()

    else:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.bind(("", 9999))
        s.listen(1)
        # sock = socket.create_connection(("", 9999))
        conn, addr = s.accept()
        current_clock = None
        previous_clock = None
        conn.settimeout(.001)
        allValues = ["0", "00000000", "0000000000000000"]

        while True:
            if(Form.isHidden()):
                break
            try:
                data = conn.recv(4096)
                allValues = data.decode('utf-8').split('#')
            except socket.timeout:
                allValues = allValues
            except socket.error:
                break
            finally:

                allValues[2] = str(allValues[2][0:16])
                # print(allValues[0])
                # print(allValues[1])
                # print(allValues[2])
                current_clock = allValues[0]
                # to avoid over-interpretation and wrong results, only run the interpreter
                # and update results on every voltage switch
                # THIS PART IS IMPORTANT!! If it does not check for the current voltage and only update
                # when the voltage changes, it could produce wrong results when we bring this over to the GPIO
                if previous_clock is None or (current_clock == "0" and previous_clock == "1") or (
                        current_clock == "1" and previous_clock == "0"):

                    json_values = interpreter.interpret(allValues, json_values)
                    previous_clock = current_clock
                    # Bus update
                    ui.lcdNumber_3.display(json_values["ui_variables"]["bus_display"])

                    # A register update
                    ui.lcdNumber_4.display(json_values["ui_variables"]["a_register_display"])

                    # B register update
                    ui.lcdNumber_2.display(json_values["ui_variables"]["b_register_display"])

                    # Output register update
                    ui.lcdNumber.display(json_values["ui_variables"]["output_register_display"])

                    ui.lcdNumber_5.display(json_values["ui_variables"]["program_counter"])

                    # Instruction Register update
                    ui.textBrowser_10.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                                "p, li { white-space: pre-wrap; }\n"
                                                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                                "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Instruction Register</span></p>\n"
                                                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br />" +
                                                                                json_values["ui_variables"][
                                                                                    "instruction_register"] + "</p></body></html>"))

                    # layman's intepretation update
                    ui.textBrowser_9.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                               "p, li { white-space: pre-wrap; }\n"
                                                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                               "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                               "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                               "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">" +
                                                                               json_values["ui_variables"][
                                                                                   "laymans"] + "</span></p>\n"
                                                                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
                                                                                                "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
                    # carry flag update
                    ui.Carry_Flag.setChecked(bool(json_values["ui_variables"]["carry_flag"]))

                    # zero flag update
                    ui.Zero_Flag.setChecked(bool(json_values["ui_variables"]["zero_flag"]))

                    # Clock update
                    ui.textBrowser_3.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                               "p, li { white-space: pre-wrap; }\n"
                                                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                                                               "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Clock</span></p>\n"
                                                                               "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">" + interpreter.voltage + "</span></p></body></html>"))
                    if allValues[0] == "1":
                        ui.textBrowser_3.setStyleSheet(
                            QtCore.QCoreApplication.translate("form", "background-color: rgb(255, 255, 204);"))
                        ui.textBrowser_3.setHtml(QtCore.QCoreApplication.translate("Form",
                                                                                   "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                                                   "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Clock</span></p>\n"
                                                                                   "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#000000;\">" + interpreter.voltage + "</span></p></body></html>"))

                    # laymans' interpretation
                    else:
                        ui.textBrowser_3.setStyleSheet(
                            QtCore.QCoreApplication.translate("form", "background-color: rgba(107, 107, 107, 150);"))

                    # Switch statement begins

                    # memory
                    #    ui.textBrowser_7.setHtml(QtCore.QCoreApplication.translate("Form",
                    #                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                    #                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                    #                                        "p, li { white-space: pre-wrap; }\n"
                    #                                       "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                    #                                      "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                    #                                     "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Memory</span></p>\n"
                    #                                    "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">"+allValues[2]+"</span></p></body></html>"))

                QtCore.QCoreApplication.processEvents()

        conn.close()
        try_setup = False
        print("closed connection")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet("""
            MainWindow {
            background-image: url("https://i.stack.imgur.com/TAJQ8.png"); 
            background-repeat: no-repeat; 
            background-position: center;
            }
    """)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    # make a file reader
    f = open('data.json')
    # load the json values into a variable
    json_vals = json.load(f)
    set_up_connection(json_vals["BE Architecture"], ui, json_vals, app, Form)
    sys.exit(0)